### ISSUE TITLE
Can't run the program

### ISSUE THREAD

**Issue by Chandler-Kluser** [pavel-krivanek/PharoChipDesigner#3]
I have created a 64bit Pharo 9.0 Image with Pharo Launcher.

I have opened playground and pressed "Do It" with the command:

```
Metacello new
  baseline: 'ChipDesigner';
  repository: 'github://pavel-krivanek/PharoChipDesigner/src';
  load.
```

I have got this error:

[![Screenshot-20210724-235738.png](https://i.postimg.cc/9FGD88JY/Screenshot-20210724-235738.png)](https://postimg.cc/3dxrWBMk)

Could you please help me to get the program running in my PC?

Thanks in advance!

**Comment by pavel-krivanek** [comment]
Hi, what platform are you using?
It looks like an older VM problem. In the launcher, try to go the the "VMs" button and update it (and maybe delete the old one).

**Comment by Chandler-Kluser** [comment]
The VM's page:
[![Screenshot-20210801-121822.png](https://i.postimg.cc/wTxgNJHJ/Screenshot-20210801-121822.png)](https://postimg.cc/RqYk5WWV)
Launching New Image:
[![Screenshot-20210801-121923.png](https://i.postimg.cc/8kMmvJw1/Screenshot-20210801-121923.png)](https://postimg.cc/xqjmDdW7)
Running README Script in Playground:
[![Screenshot-20210801-122326.png](https://i.postimg.cc/6p3ZMyV4/Screenshot-20210801-122326.png)](https://postimg.cc/MvCXTZFz)

**Comment by Chandler-Kluser** [comment]
I have also tried to run it manually by doing:
- download the repository
- add the /src folder to the Pharo local files
- run the following command in Playground:
```
Metacello new
  baseline: 'ChipDesigner';
  repository: '/home/chandler/Pharo/images/Pharo 9.0 - 64bit (stable)/pharo-local/PharoChipDesigner-master/src/';
  load.
```
and I have got:
[![Screenshot-20210801-142410.png](https://i.postimg.cc/MK39zcDq/Screenshot-20210801-142410.png)](https://postimg.cc/dLd2BVpx)
Apparently, there is no .mcz file to load

**Comment by Chandler-Kluser** [comment]
I have compiled it in pharo launcher in ubuntu with no problems!
